[build]
builder = "NIXPACKS"

[deploy]
startCommand = "java -Dserver.port=$PORT $JAVA_OPTS -jar target/*.jar"
healthcheckPath = "/actuator/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
